### ISSUE TITLE
May be potential bugs.

### ISSUE THREAD

**Issue by CGLemon** [kobanium/TamaGo#12]
### 1. In the ```pucb.py```,  the value should not be zero if there is no visits.
```python
exploration = np.divide(value_sum, children_visits, \
  out=np.zeros_like(value_sum), where=(children_visits != 0))
```

The value should be 0.5 (draw value)?
```python
exploration = np.divide(value_sum, children_visits, \
  out=np.zeros_like(value_sum) + 0.5, where=(children_visits != 0))
```

### 2. In the ```tree.py```,  update the nodes via ```reverse_path```. Not ```path```.

```python
    def process_mini_batch(self, board: GoBoard): # pylint: disable=R0914
    ......
            if path:
                value = value_dist[0] + value_dist[1] * 0.5

                reverse_path = list(reversed(path))
                leaf = reverse_path[0]

                self.node[leaf[0]].set_leaf_value(leaf[1], value)

                for index, child_index in path:
                    self.node[index].update_child_value(child_index, value)
                    self.node[index].update_node_value(value)
                    value = 1.0 - value
```
May use ```reverse_path``` instead of ```path```?

```python
    def process_mini_batch(self, board: GoBoard): # pylint: disable=R0914
    ......
            if path:
                value = value_dist[0] + value_dist[1] * 0.5

                reverse_path = list(reversed(path))
                leaf = reverse_path[0]

                self.node[leaf[0]].set_leaf_value(leaf[1], value)

                for index, child_index in reverse_path:
                    self.node[index].update_child_value(child_index, value)
                    self.node[index].update_node_value(value)
                    value = 1.0 - value
```

**Comment by kobanium** [comment]
It is correct to set the Q(a) of an unexplored node to 0 (lose). Minigo's experiment did not much better when using 0.5 (draw) for the initial value of Q(a) .
https://cloudygo.com/RESULTS?bucket=v12-19x19
I'd rather use FPU than set the default value for Q(a).

Your point about using reverse path instead of path is correct. That's simply my mistake.

**Comment by CGLemon** [comment]
Interesting result. The note said "Still it's what the paper says and we expected it to fail quickly so we tested it. I quickly read the AlphaGo Zero paper again. The method of paper is to set the unvisited node as 0.

**Comment by kobanium** [comment]
We implemented [aobazero](https://github.com/kobanium/aobazero) as a copy of AlphaZero for shogi. In aobazero, the initial value of Q(a) was initially set to a draw situation, but black won too much and reinforcement learning was not progressive well.
We believe the paper my be mistaken about value range for Q(a). I use [0.0, 1.0] for Q(a)'s value range and set initial value of Q(a) to 0.0.
