### ISSUE TITLE
May be a bug

### ISSUE THREAD

**Issue by shengkelong** [kobanium/TamaGo#56]
In nn/feature.py
`
def generate_rl_target_data(board: GoBoard, improved_policy_data: str, sym: int=0) -> np.ndarray:

    split_data = improved_policy_data.split(" ")[1:]
    target_data = [1e-18] * len(board.board)
    for datum in split_data[1:]:
        pos, target = datum.split(":")
        coord = board.coordinate.convert_from_gtp_format(pos)
        target_data[coord] = float(target)`

Maybe the second [1:] should be removed, it removes the number of child nodes twice

**Comment by kobanium** [comment]
Thank you. As you mentioned, it is bug. I will fix it.
