### ISSUE TITLE
I cannot use TamaGo on Gogui on Mac

### ISSUE THREAD

**Issue by kwakai3** [kobanium/TamaGo#79]
I cannot use TamaGo on Gogui on Mac.
 I tried to register the command python3 /Users/user/TamaGo-main/main.py --model model/rl-model.bin but failed and got the message "囲碁プログラムはどのコメンドにも応答しません。..."

**Comment by CGLemon** [comment]
Looks your command is correct. May you try to execute via terminal? The terminal will show more verbose.

**Comment by kwakai3** [comment]
CGLemon: Thank you for your comment. The program successfully ran in the terminal.

**Comment by CGLemon** [comment]
I see. I think you use relative path of model in the command. Please use absolute path instead of relative path.

**Comment by kobanium** [comment]
Please check GTP shell console when you use TamaGo on Gogui and tell us messages from console.

**Comment by kwakai3** [comment]
Thank you very much for your comment. I could resolve the issue by checking the message from GTP shell console.
