### ISSUE TITLE
A minor  mistake of network structure.

### ISSUE THREAD

**Issue by CGLemon** [kobanium/TamaGo#8]
In the ```nn\network\res_block.py```, the forwarding is

```python
def forward(self, input_plane: torch.Tensor) -> torch.Tensor:
    hidden_1 = self.relu(self.bn1(self.conv1(input_plane)))
    hidden_2 = self.relu(self.bn2(self.conv2(hidden_1)))
    return input_plane + hidden_2
```

The correct block forwarding should be

```python
def forward(self, input_plane: torch.Tensor) -> torch.Tensor:
    hidden_1 = self.relu(self.bn1(self.conv1(input_plane)))
    hidden_2 = self.bn2(self.conv2(hidden_1))
    return self.relu(input_plane + hidden_2)
```

**Comment by kobanium** [comment]
Thank you for checking.  
I was mistaken about the accuracy of the residual block for variants. I always use pre-activation form.  
https://arxiv.org/pdf/1603.05027.pdf
After changing forward implemention, I retrain network. This is little stronger than v0.2.0 implementation.

**Comment by CGLemon** [comment]
It is interesting paper. I quickly check the KataGo network structure. I sure that KataGo  used the full pre-activation block. The full pre-activation block should be like

```python
def forward(self, input_plane: torch.Tensor) -> torch.Tensor:
    hidden_1 = self.conv1(self.relu(self.bn1(input_plane)))
    hidden_2 = self.conv2(self.relu(self.bn2(hidden_1)))
    return input_plane + hidden_2
```

Does Ray use full pre-activation block?

**Comment by kobanium** [comment]
Ray use pre-activation residual blocks with squeeze-and-excitation module.  
It may not be as effective as this issue, I suggest you give it a try.
